loadstring(game:HttpGet("https://raw.githubusercontent.com/SourcexCode/D3V1LS-Source/main/Script/Premium/Premium-Commands%26Whitelist.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/SourcexCode/D3V1LS-Source/main/Script/Anti-Mod/Anti-Mod.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/SourcexCode/D3V1LS-Source/main/Script/Script/D3V1LS-Source.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/SourcexCode/D3V1LS-Source/main/Script/Sofie/Commands/OwnerTeleporter.txt"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/SourcexCode/D3V1LS-Source/main/Script/Emoijs/Emoijs-Script-Redirect.lua"))()
